name: MinevuiCore
version: 1.1.2
main: com.lvdat.minevuicore.MinevuiCore
author: lvdat
api-version: 1.20.6
commands:
  minevui:
    description: Command for MinevuiCore
    usage: /minevui <subcommand>